In [4]:
import pandas as pd
from datetime import datetime

# Load CSV files
students = pd.read_csv(r'C:\Users\HP\Desktop\Students.csv')
complaints = pd.read_csv(r'C:\Users\HP\Desktop\Complaints.csv')
requests = pd.read_csv(r'C:\Users\HP\Downloads\Requests.csv')

In [5]:
students.head()  #Printing first 5 records of student dataset

,Student ID,Name,Age,Department,Room no,Email ID,Phone no,Password
0,S001,Ali Khan,19,CS,101,ali.khan@hostel.com,3001234501,pass001
1,S002,Ayesha Malik,18,EE,203,ayesha.malik@hostel.com,3001234502,pass002
2,S003,Ahmed Raza,20,BBA,305,ahmed.raza@hostel.com,3001234503,pass003
3,S004,Sania Iqbal,21,CS,118,sania.iqbal@hostel.com,3001234504,pass004
4,S005,Hammad Shah,19,SE,214,hammad.shah@hostel.com,3001234505,pass005

In [7]:
#this data contains following columns
students.columns

Index(['Student ID', 'Name', 'Age ', 'Department', 'Room no ', 'Email ID',
       'Phone no', 'Password'],
      dtype='object')

In [8]:
print(students.info())  #total number of entries, data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  100 non-null    object
 1   Name        100 non-null    object
 2   Age         100 non-null    int64
 3   Department  100 non-null    object
 4   Room no     100 non-null    int64
 5   Email ID    100 non-null    object
 6   Phone no    100 non-null    int64
 7   Password    100 non-null    object
dtypes: int64(3), object(5)
memory usage: 6.4+ KB
None

In [12]:
#simple statistical analysis for students_csv
print("Average age of Students in Hostel is:\t",students['Age '].mean(),"years")
print("Standard deviation Age about mean is: \t",students['Age '].std(),"years")
print("Minimum Age of Students in Hostel is:\t",students['Age '].min(),"years")
print("Maximum Age of Students in Hostel is:\t",students['Age '].max(),"years")

Average age of Students in Hostel is:	 19.67 years
Standard deviation Age about mean is: 	 1.2717203809299948 years
Minimum Age of Students in Hostel is:	 18 years
Maximum Age of Students in Hostel is:	 22 years

In [13]:
students.describe()  #descriptive analysis o students data set

            Age     Room no       Phone no
count  100.00000  100.000000  1.000000e+02
mean    19.67000  266.270000  3.001235e+09
std      1.27172  128.951471  2.901149e+01
min     18.00000  101.000000  3.001235e+09
25%     19.00000  123.000000  3.001235e+09
50%     20.00000  220.500000  3.001235e+09
75%     21.00000  350.000000  3.001235e+09
max     22.00000  520.000000  3.001235e+09

In [18]:
#Changing data types for the variable appropriately
#print(students['Room no '].astype("string").head(1))
print(students['Department'].astype("string").head(1))

0    CS
Name: Department, dtype: string

In [25]:
complaints.columns

Index(['Complaint ID', 'Student ID', 'Category', 'Complaint', 'Date',
       'Status'],
      dtype='object')

In [26]:
complaints.isnull().sum()

Complaint ID    0
Student ID      0
Category        0
Complaint       0
Date            0
Status          0
dtype: int64

In [27]:
complaints.head(3)

,Complaint ID,Student ID,Category,Complaint,Date,Status
0,C001,S014,Maintenance,Ceiling fan in Room 403 is making loud noise a...,10/02/2025,Pending
1,C002,S027,Cleanliness,Washroom on Floor 5 has not been cleaned prope...,11/02/2025,Pending
2,C003,S063,Noise,Students in Room 117 play loud music late at n...,12/02/2025,Resolved

In [28]:
requests

,Student ID,Request ID,Request Type,Request Description,Date,Status
0,S001,R001,Outpass,Requesting permission to leave campus.,11/25/2025,Pending
1,S022,R002,Outpass,Outpass needed for short-duration leave.,11/26/2025,Approved
2,S003,R003,Outpass,Student requests outpass for personal reasons.,11/27/2025,Approved
3,S034,R004,Outpass,Outpass required for urgent matter.,11/28/2025,Approved
4,S055,R005,Outpass,Outpass requested for scheduled appointment.,11/29/2025,Pending

In [29]:
requests.isnull().sum()

Student ID             0
Request ID             0
Request Type           0
Request Description    0
Date                   0
Status                 0
dtype: int64

In [33]:
requests.duplicated().sum()

np.int64(0)

In [22]:
#data cleaning
print("Nulls in Student data: ",students.isnull().sum())

Nulls in Student data:  Student ID    0
Name          0
Age           0
Department    0
Room no       0
Email ID      0
Phone no      0
Password      0
dtype: int64

In [23]:
#Searching for missing values
print("Missing Values indicated by 'false' in rows")
students.isna()

Missing Values indicated by 'false' in rows

,Student ID,Name,Age,Department,Room no,Email ID,Phone no,Password
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False

In [24]:
#Checking for duplicates
print("no. of duplicate records : ",students.duplicated().sum())  # Count duplicates

no. of duplicate records :  0

In [34]:
complaints.isnull().sum()

Complaint ID    0
Student ID      0
Category        0
Complaint       0
Date            0
Status          0
dtype: int64

In [35]:
requests.isnull().sum()

Student ID             0
Request ID             0
Request Type           0
Request Description    0
Date                   0
Status                 0
dtype: int64

In [39]:
complaints.tail(3)

,Complaint ID,Student ID,Category,Complaint,Date,Status
7,C008,S089,Roommate Issue,Roommate keeps bringing friends into the room ...,15/02/2025,In progress
8,C009,S075,Out-Pass Issue,Out-pass request was submitted two days ago bu...,15/02/2025,Pending
9,C010,S020,Other,Water dispenser on Floor 2 is empty most of th...,16/02/2025,Resolved

In [40]:
requests.tail(3)

,Student ID,Request ID,Request Type,Request Description,Date,Status
2,S003,R003,Outpass,Student requests outpass for personal reasons.,11/27/2025,Approved
3,S034,R004,Outpass,Outpass required for urgent matter.,11/28/2025,Approved
4,S055,R005,Outpass,Outpass requested for scheduled appointment.,11/29/2025,Pending

In [41]:
import pandas as pd
from datetime import datetime

# Load CSV files
students = pd.read_csv(r'C:\Users\HP\Desktop\Students.csv')
complaints = pd.read_csv(r'C:\Users\HP\Desktop\Complaints.csv')
requests = pd.read_csv(r'C:\Users\HP\Downloads\Requests.csv')

print("[NUCES HOSTEL MANAGEMENT SYSTEM]")

# -----------------------------
#      STUDENT FUNCTIONS
# -----------------------------

def complaint_status():
    while True:
        comp_ID = input("Enter Complaint ID in format C### : ") #asks user for 

        if comp_ID in complaints['Complaint ID'].astype(str).values:
            print("Complaint is in database.")

            status = complaints.loc[complaints['Complaint ID'] == comp_ID, 'Status']
            print(f"Status for {comp_ID} is {status}")

            more = int(input("1 | Check more complaint's status\n2 | Exit\n"))
            if more == 1:
                continue
            elif more == 2:
                return  # <-- FIXED (goes back to menu)
            else:
                print("Invalid value entered.")
        else:
            print("Complaint ID is incorrect. Try again.")


def complaint_id_generator():
    last_id = complaints['Complaint ID'].iloc[-1]
    ID = int(last_id[1:]) + 1
    return f"C{ID:03d}"


def file_new_complaint():
    categories = ["Maintenance", "Cleanliness", "Noise", "Wifi/Network", "Food",
                  "Discipline", "Roomate Issue", "Outpass Issue", "Other"]

    st_id = input("Enter Student ID in format S### : ")
    complaint_id = complaint_id_generator()
    print("Assigned Complaint ID:", complaint_id)

    print("\t\t\tChoose Category\t\t\t")
    for c in categories:
        print("-", c)

    selected_cat = input("Category : ")
    while selected_cat not in categories:
        print("Invalid selection! Please choose a category from the menu.")
        selected_cat = input("Category : ")

    # At this point, selected_cat is guaranteed to be valid
    print(f"You selected: {selected_cat}")


    description = input("Describe your complaint in one sentence : ")
    current_date = date_generator()

    new_complaint = {
        "Complaint ID": complaint_id,
        "Student ID": st_id,
        "Category": selected_cat,
        "Complaint": description,
        "Date": current_date,
        "Status": "Pending",
    }

    complaints.loc[len(complaints)] = new_complaint
    print("Complaint has been successfully registered!")
    return  # <-- Return to menu


def request_forum():
    st_id = input("Enter Student ID in format S### : ")

    query = input("1 | View Old Requests\n2 | Apply for Request\n3 | Check Request Status\n")

    if query == '1':
        view_old_req()
    elif query == '2':
        new_req()
    else:
        request_status()


def view_old_req():
    req_id = input("Enter Request ID in format R###: ")

    old_req = requests.loc[requests['Request ID'] == req_id,
                           ['Request Description', 'Date', 'Status']]

    if old_req.empty:
        print(f"No request found with ID {req_id}.")
        return

    req_row = old_req.iloc[0]

    print("\n--- Request Details ---")
    print(f"Request ID       : {req_id}")
    print(f"Description      : {req_row['Request Description']}")
    print(f"Date             : {req_row['Date']}")
    print(f"Status           : {req_row['Status']}")
    print("------------------------\n")
    return


def date_generator():
    date_of_req = datetime.now().strftime("%d/%m-%y")
    return date_of_req


def req_num_generator():
    last_id = requests['Request ID'].iloc[-1]
    ID = int(last_id[1:]) + 1
    return f"R{ID:03d}"


def new_req():
    st_id = input("Enter Student ID in format S### : ")
    request_id = req_num_generator()
    print("Assigned Request ID:", request_id)

    description = input("Describe your request in one sentence : ")
    current_date = date_generator()

    new_request = {
        "Student ID": st_id,
        "Request ID": request_id,
        "Request Type": "Outpass",
        "Request Description": description,
        "Date": current_date,
        "Status": "Pending"
    }

    requests.loc[len(requests)] = new_request
    print("Request has been successfully registered!")
    return


def request_status():
    while True:
        request_id = input("Enter Request ID in format R### : ")

        if request_id in requests['Request ID'].astype(str).values:
            print("Request is in Hostel Database")
            print(requests.loc[requests['Request ID'] == request_id, ['Status']])
        else:
            print("Incorrect Request ID. Try again.")
            continue

        return  # <-- back to menu


# -----------------------------
#           MENUS
# -----------------------------

def menu():
    while True:    # <-- FIXED (menu repeats)
        print("\t\t\t NU HOSTEL COMPLAINT SYSTEM \t\t\t")
        choice = input("1 | complain status\n2 | file_new_complaint\n3 | Request Forum\n4 | Log out\n")

        if choice == "1":
            complaint_status()
        elif choice == "2":
            file_new_complaint()
        elif choice == "3":
            request_forum()
        elif choice == "4":
            print("Logging out...")
            return  # <-- back to student_login()
        else:
            print("Invalid choice. Try again.")


# -----------------------------
#       WARDEN FUNCTIONS
# -----------------------------

warden = {"Name": "Shazia Jameel", "ID": "W000", "Password": "Warden1234"}


def view_complaints():
    print(complaints)

def view_requests():
    print("\n--- ALL OUTPASS REQUESTS ---")
    if requests.empty:
        print("No requests found.")
    else:
        print(requests.to_string(index=False))

def update_request_status():
    global requests

    while True:
        req_id = input("Enter Request ID in format R###: ")

        if req_id not in requests['Request ID'].astype(str).values:
            print("Invalid Request ID! Try again.")
            continue

        print("\nUpdate Status Options:")
        print("1 | Pending")
        print("2 | Approved")
        print("3 | Rejected")
        print("4 | Exit")

        choice = input("Select: ")

        if choice == "1":
            new_status = "Pending"
        elif choice == "2":
            new_status = "Approved"
        elif choice == "3":
            new_status = "Rejected"
        elif choice == "4":
            return
        else:
            print("Invalid input.")
            continue

        requests.loc[requests['Request ID'] == req_id, "Status"] = new_status
        requests.to_csv("Requests.csv", index=False)

        print(f"\nRequest ID {req_id} updated to {new_status}.")
        print(requests[requests['Request ID'] == req_id].to_string(index=False))

        more = input("Update another? (yes/no): ").lower()
        if more != "yes":
            return



def update_complaint_status():
    global complaints

    while True:
        ID = input("Enter the Complaint ID: ")

        if ID not in complaints['Complaint ID'].values:
            print("Invalid Complaint ID! No record found")
            continue

        print("Options:\n1 | Pending\n2 | In progress\n3 | Resolved\n | Exit\n")
        status = int(input("Select: "))

        if status == 1:
            new_status = 'Pending'
        elif status == 2:
            new_status = 'In progress'
        elif status == 3:
            new_status = 'Resolved'
        elif status == 4:
            return
        else:
            print("Invalid option!")
            continue

        complaints.loc[complaints["Complaint ID"] == ID, "Status"] = new_status
        complaints.to_csv("complaints.csv", index=False)

        record = complaints[complaints['Complaint ID'] == ID]
        print(f"Complaint ID {ID} updated to {new_status}")
        print(record.to_string(index=False))

        more = input("Update another? (yes/no): ").lower()
        if more != 'yes':
            return


def filter_complaints():
    print("Filter by:\n1 | Category\n2 | Date\n3 | Student ID")
    choice = input("Enter your choice: ")

    if choice == "1":
        cat = input("Enter category: ")
        filtered = complaints[complaints['Category'].str.lower() == cat.lower()]
    elif choice == "2":
        date = input("Enter date (YYYY-MM-DD): ")
        filtered = complaints[complaints['Date'] == date]
    elif choice == "3":
        sid = input("Enter Student ID: ")
        filtered = complaints[complaints['Student ID'] == sid]
    else:
        print("Invalid choice!")
        return

    if filtered.empty:
        print("No complaints found.")
    else:
        print(filtered.to_string(index=False))

    return


def file_warning():
    student_id = input("Enter Student ID: ")
    category = input("Enter Category: ")
    comp_description = input("Enter Description: ")

    last_id = complaints['Complaint ID'].iloc[-1]
    new_id = int(last_id[1:]) + 1

    new_row = pd.DataFrame([{
        "Complaint ID": f"C{new_id:03d}",
        "Student ID": student_id,
        "Category": category,
        "Date": datetime.now().strftime("%Y-%m-%d"),
        "Status": "Pending",
        "Complaint": comp_description
    }])

    complaints.loc[len(complaints)] = new_row.iloc[0]
    complaints.to_csv("complaints.csv", index=False)

    print("Complaint/Warning filed successfully!")
    return


def warden_menu():
    while True:
        print("\n--- WARDEN MENU ---")
        print("1 | View all complaints")
        print("2 | Update complaint status")
        print("3 | Filter complaints")
        print("4 | File complaint/warning")
        print("5 | View Outpass Requests")
        print("6 | Update Request Status")
        print("7 | Log out")

        choice = input("Enter choice: ")

        if choice == "1":
            view_complaints()
        elif choice == "2":
            update_complaint_status()
        elif choice == "3":
            filter_complaints()
        elif choice == "4":
            file_warning()
        elif choice == "5":
            view_requests()
        elif choice == "6":
            update_request_status()
        elif choice == "7":
            print("Logging out...")
            return
        else:
            print("Invalid choice!")


# -----------------------------
#            LOGIN
# -----------------------------

def student_login():
    while True:
        student_id = input("Enter Student ID: ")
        password = input("Enter Password: ")

        record = students[students["Student ID"] == student_id]

        if not record.empty and record.iloc[0]["Password"] == password:
            print("Login successful!")
            menu()        # returns when user logs out
            return        # back to login()
        else:
            print("Incorrect ID or Password.")
            retry = input("Retry? (yes/no): ").lower()
            if retry != "yes":
                print("Returning to main menu...")
                return


def warden_login():
    while True:
        war_id = input("Enter Warden ID: ")
        war_password = input("Enter Password: ")

        if war_id == warden["ID"] and war_password == warden["Password"]:
            print("Login successful!")
            warden_menu()
            return
        else:
            print("Incorrect ID or Password.")
            retry = input("Retry? (yes/no): ").lower()
            if retry != "yes":
                print("Returning to main menu...")
                return


def login():
    while True:
        choice = input("Enter the number of your choice:\n1 | Student\n2 | Warden\n0 | Exit\n")

        if choice == "1":
            student_login()
        elif choice == "2":
            warden_login()
        elif choice == "0":
            print("Exiting system...")
            break
        else:
            print("Invalid choice. Try again.")


# Run system
login()

[NUCES HOSTEL MANAGEMENT SYSTEM]

Enter the number of your choice:
1 | Student
2 | Warden
0 | Exit
 1
Enter Student ID:  S002
Enter Password:  pass002

Login successful!
			 NU HOSTEL COMPLAINT SYSTEM

1 | complain status
2 | file_new_complaint
3 | Request Forum
4 | Log out
 2
Enter Student ID in format S### :  S002

Assigned Complaint ID: C011
			Choose Category
- Maintenance
- Cleanliness
- Noise
- Wifi/Network
- Food
- Discipline
- Roomate Issue
- Outpass Issue
- Other

Category :  Maintenance
Describe your complaint in one sentence :  Room lights won't turn on

Complaint has been successfully registered!
			 NU HOSTEL COMPLAINT SYSTEM

1 | complain status
2 | file_new_complaint
3 | Request Forum
4 | Log out
 4

Logging out...

Enter the number of your choice:
1 | Student
2 | Warden
0 | Exit
 0

Exiting system...

In [44]:
complaints.tail(3)

,Complaint ID,Student ID,Category,Complaint,Date,Status
8,C009,S075,Out-Pass Issue,Out-pass request was submitted two days ago bu...,15/02/2025,Pending
9,C010,S020,Other,Water dispenser on Floor 2 is empty most of th...,16/02/2025,Resolved
10,C011,S002,Maintenance,Room lights won't turn on,01/12-25,Pending

In [43]:
requests.tail(3)

,Student ID,Request ID,Request Type,Request Description,Date,Status
2,S003,R003,Outpass,Student requests outpass for personal reasons.,11/27/2025,Approved
3,S034,R004,Outpass,Outpass required for urgent matter.,11/28/2025,Approved
4,S055,R005,Outpass,Outpass requested for scheduled appointment.,11/29/2025,Pending